### PR TITLE
Sugestões

### PR DESCRIPTION
**Pull request by mateusvahl**
Algumas sugestões as 4:20 am (y)

### CODE REVIEW

**Comment by suissa** [comment]
KD?? ehhehehe

**Comment by mauricionr** [comment]
https://github.com/mateuspv/workshop-js-funcional-free/commit/c851b70cdb85c1143c55a6f9ad5e7ba147a6557b

**Comment by suissa** [comment]
404

**Comment by mateusvahl** [comment]
Exclui ontem ._. kkkk depois mando de novo

**Comment by suissa** [comment]
OK

**Pull request closed without merging**
